#!/bin/bash

# NOTE: uses standard container names/ports et all
# TODO: use env vars or something

if [ -t 0 ] ; then
        TERM_FLAG="-it"
    else
        TERM_FLAG="-i"
    fi

case `basename $0` in
    sql_access_docker)
    if [ -z $1 ]; then
      SQL_USER=promis
    else
      SQL_USER=$1
    fi
    if [ -z $2 ]; then
      SQL_DB=promisdb
    else
      SQL_DB=$2
    fi
    vagrant docker-exec $TERM_FLAG db.promis -- psql -U $SQL_USER $SQL_DB
    ;;

    sql_access_psql)
    psql -h localhost -p 5432 -U promis promisdb # TODO: what if port is different?
    ;;

    backend_shell)
    vagrant docker-exec $TERM_FLAG api.promis -- python promis/manage.py shell
    ;;

    backend_command)
    vagrant docker-exec $TERM_FLAG api.promis -- python promis/manage.py $*
    ;;

    backend_bash)
    vagrant docker-exec $TERM_FLAG api.promis -- bash
    ;;
esac
