# TODO maybe nginx:alpine?
# TODO: special rights on /etc/ssl.d/
FROM nginx:1.11.5
ADD index.html /var/www/promis/
ADD fonts /var/www/promis/fonts/
ADD data /var/www/promis/data/
ADD css /var/www/promis/css/
ADD js /var/www/promis/js/
# full version until webpack bundle
ADD cesium /var/www/promis/cesium/
ADD download /var/www/promis/download/

# This doesn't contain any replacements
ADD nginx.conf /etc/nginx/

# Configs generated by deploy
ADD deploy/promis.conf /etc/nginx/
ADD deploy/promis_api.yaml /var/www/promis/api/

RUN chgrp nginx /etc/ssl/private
RUN chmod g+x,g+r /etc/ssl/private
