# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-16 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0002_auto_20170213_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='channels',
            name='parser_func',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parser_func', to='backend_api.Functions'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='space_projects',
            name='description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sp_description', to='backend_api.Translations'),
        ),
    ]
