# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-16 21:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0003_auto_20170216_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channels',
            name='parser_func',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parser_func', to='backend_api.Functions'),
        ),
        migrations.AlterField(
            model_name='channels',
            name='quicklook',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_api.Functions'),
        ),
        migrations.AlterField(
            model_name='translations',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
