# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-23 11:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0004_auto_20170216_2125'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Channels',
            new_name='Channel',
        ),
        migrations.RenameModel(
            old_name='Devices',
            new_name='Device',
        ),
        migrations.RenameModel(
            old_name='Documents',
            new_name='Document',
        ),
        migrations.RenameModel(
            old_name='Functions',
            new_name='Function',
        ),
        migrations.RenameModel(
            old_name='Measurements',
            new_name='Measurement',
        ),
        migrations.RenameModel(
            old_name='Parameters',
            new_name='Parameter',
        ),
        migrations.RenameModel(
            old_name='Sessions',
            new_name='Session',
        ),
        migrations.RenameModel(
            old_name='Space_projects',
            new_name='Space_project',
        ),
        migrations.RenameModel(
            old_name='Translations',
            new_name='Translation',
        ),
        migrations.RenameModel(
            old_name='Units',
            new_name='Unit',
        ),
        migrations.RenameModel(
            old_name='Values',
            new_name='Value',
        ),
    ]
