# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 12:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0006_auto_20170306_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('language_code', models.CharField(db_index=True, max_length=15)),
            ],
            options={
                'db_table': 'channels_translation',
                'db_tablespace': '',
                'abstract': False,
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='DeviceTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('language_code', models.CharField(db_index=True, max_length=15)),
            ],
            options={
                'db_table': 'devices_translation',
                'db_tablespace': '',
                'abstract': False,
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FunctionTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('language_code', models.CharField(db_index=True, max_length=15)),
            ],
            options={
                'db_table': 'functions_translation',
                'db_tablespace': '',
                'abstract': False,
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ParameterTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('language_code', models.CharField(db_index=True, max_length=15)),
            ],
            options={
                'db_table': 'parameters_translation',
                'db_tablespace': '',
                'abstract': False,
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Space_projectTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('language_code', models.CharField(db_index=True, max_length=15)),
            ],
            options={
                'db_table': 'space_projects_translation',
                'db_tablespace': '',
                'abstract': False,
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='UnitTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.TextField()),
                ('long_name', models.TextField()),
                ('language_code', models.CharField(db_index=True, max_length=15)),
            ],
            options={
                'db_table': 'units_translation',
                'db_tablespace': '',
                'abstract': False,
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ValueTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('language_code', models.CharField(db_index=True, max_length=15)),
            ],
            options={
                'db_table': 'values_translation',
                'db_tablespace': '',
                'abstract': False,
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.AlterModelManagers(
            name='channel',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_plain_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='device',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_plain_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='function',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_plain_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='parameter',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_plain_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='space_project',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_plain_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='unit',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_plain_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='value',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_plain_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='channel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='device',
            name='description',
        ),
        migrations.RemoveField(
            model_name='device',
            name='name',
        ),
        migrations.RemoveField(
            model_name='function',
            name='description',
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='description',
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='name',
        ),
        migrations.RemoveField(
            model_name='space_project',
            name='description',
        ),
        migrations.RemoveField(
            model_name='space_project',
            name='name',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='long_name',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='short_name',
        ),
        migrations.RemoveField(
            model_name='value',
            name='description',
        ),
        migrations.RemoveField(
            model_name='value',
            name='name',
        ),
        migrations.DeleteModel(
            name='Translation',
        ),
        migrations.AddField(
            model_name='valuetranslation',
            name='master',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='backend_api.Value'),
        ),
        migrations.AddField(
            model_name='unittranslation',
            name='master',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='backend_api.Unit'),
        ),
        migrations.AddField(
            model_name='space_projecttranslation',
            name='master',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='backend_api.Space_project'),
        ),
        migrations.AddField(
            model_name='parametertranslation',
            name='master',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='backend_api.Parameter'),
        ),
        migrations.AddField(
            model_name='functiontranslation',
            name='master',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='backend_api.Function'),
        ),
        migrations.AddField(
            model_name='devicetranslation',
            name='master',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='backend_api.Device'),
        ),
        migrations.AddField(
            model_name='channeltranslation',
            name='master',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='backend_api.Channel'),
        ),
        migrations.AlterUniqueTogether(
            name='valuetranslation',
            unique_together=set([('language_code', 'master')]),
        ),
        migrations.AlterUniqueTogether(
            name='unittranslation',
            unique_together=set([('language_code', 'master')]),
        ),
        migrations.AlterUniqueTogether(
            name='space_projecttranslation',
            unique_together=set([('language_code', 'master')]),
        ),
        migrations.AlterUniqueTogether(
            name='parametertranslation',
            unique_together=set([('language_code', 'master')]),
        ),
        migrations.AlterUniqueTogether(
            name='functiontranslation',
            unique_together=set([('language_code', 'master')]),
        ),
        migrations.AlterUniqueTogether(
            name='devicetranslation',
            unique_together=set([('language_code', 'master')]),
        ),
        migrations.AlterUniqueTogether(
            name='channeltranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
